import Link from 'next/link';
import { ArrowUpRight, ArrowDownToLine, Scale, FileCheck2 } from 'lucide-react';
import type { Submission } from '@/lib/submission';
import { euro } from '@/lib/formatting';
import { Badge, EvidenceRefs, FinancialTable, SectionTitle } from './Primitives';
import DecisionRegister from './DecisionRegister';

const navigation = [['summary','Executive summary'],['statements','Financial statements'],['schedules','Supporting schedules'],['reconciliations','Reconciliations'],['decisions','Decisions'],['evidence','Evidence'],['uncertainties','Uncertainties'],['board','Board recommendation'],['trail','AI review trail']];
export default function Report({submission:s,assessor=false}:{submission:Submission;assessor?:boolean}) {
 const a=s.metrics;
 return <div className="site-shell">
  <a href="#main" className="skip-link">Skip to content</a>
  <aside className="sidebar">
   <Link href="/" className="brand"><span className="brand-mark"><Scale size={21}/></span><span>DPI<span>FORENSIC REVIEW</span></span></Link>
   <div className="sidebar-case"><span className="eyebrow">CASE FILE</span><b>{s.caseId}</b><small>Management accounting</small></div>
   <nav aria-label="Main navigation">{navigation.map(([id,title],i)=><a key={id} href={`${assessor?'/':''}#${id}`}><span>{String(i+1).padStart(2,'0')}</span>{title}</a>)}<Link href="/review" className={assessor?'active':''}><FileCheck2 size={16}/>Assessor review<ArrowUpRight size={14}/></Link></nav>
   <div className="sidebar-bottom"><span className="live-dot"/>Evidence-led reconstruction<p>31 August 2026<br/>All amounts in EUR</p><a href="/submission.json" download="DPI-HT-01-submission.json"><ArrowDownToLine size={15}/>Download submission</a></div>
  </aside>
  <div className="main-column">
   <header className="topbar"><span>Bad Decisions Capital <span className="separator">/</span> Investment review</span><div><Badge text="QUALIFIED"/><Link href={assessor?'/':'/review'}>{assessor?'Full case website':'Assessor view'}<ArrowUpRight size={14}/></Link></div></header>
   <main id="main">
    <section id="summary" className="hero">
     <span className="eyebrow">{assessor?'ASSESSOR WORKSPACE':'FINANCIAL RECONSTRUCTION'} <span className="dot-divider">·</span> {s.caseId}</span>
     <div className="hero-heading"><h1>{assessor?<>The evidence.<br/><span>The decisions.</span></>:<>Divorce Party<br/><span>International Ltd.</span></>}</h1><span className="report-stamp">REPORTING DATE<strong>31 AUG<br/>2026</strong></span></div>
     <p className="hero-description">{assessor?'A compact review of every decision, its evidence and its remaining uncertainty.':'Reconstructing the financial position behind the management story. A transparent view of what the evidence supports, and what remains open.'}</p>
     <div className="hero-meta"><span>Prepared for university assessment</span><span>{s.student.name} · {s.student.id}</span><span>1 January – 31 August 2026</span></div>
    </section>
    <div className="qualification"><span className="qualification-icon">!</span><div><strong>Adopted reconstruction. Student certification {s.certification.status}.</strong><p>Opening PPE, depreciation and opening equity use adopted assumptions that are not independently verified from the available original evidence. All 100 questions, categories and review tiers match the supplied group reference. Arithmetic agreement does not resolve the evidence gaps.</p><p><a href="#U01">Inventory conflict: {euro(a.inventoryDifference)}</a> · <a href="#U02">Insurance: no supported amount recognised; actual amount unknown</a> · <a href="#U05">€2,000 disposal quote: no present obligation, no provision</a></p></div></div>
    <div className="metric-grid">
     <Metric label="Corrected profit" value={euro(a.knownResult)} status="PROVISIONAL" note="Adopted reconstruction; evidence qualifications remain"/>
     <Metric label="Closing bank cash" value={euro(a.closingCash)} status="CONFIRMED" note="Agrees with external bank confirmation"/>
     <Metric label="Total assets" value={euro(a.totalAssets)} status="QUALIFIED" note="Includes unverified opening PPE and depreciation assumptions"/>
     <Metric label="Closing equity" value={euro(a.closingEquity)} status="QUALIFIED" note="Opening equity + profit − owner distributions"/>
    </div>
    <InventorySensitivity submission={s}/>
    {assessor?<>
     <section className="section" id="review-overview"><SectionTitle eyebrow="REVIEW COVERAGE" title="A complete register. An honest status."/><div className="review-stats"><Stat label="Decisions" value={s.decisionCoverage.total}/><Stat label="Operational" value={s.decisionCoverage.operational}/><Stat label="Material judgments" value={s.decisionCoverage.material}/><Stat label="Low confidence" value={s.decisions.filter(d=>d.confidence==='Low').length}/><Stat label="Personally reviewed material" value={s.certification.materialReviewed}/></div><p>Original agent reviews populated: <b>{s.aiReviewTrail.materialJudgmentsPopulated}/25</b>. Accounting disagreements: <b>{s.aiReviewTrail.accountingDisagreements}</b>. Confidence differences: <b>{s.aiReviewTrail.confidenceDifferences}</b>. Student Certification: <b>{s.certification.status}</b>. All {s.certification.materialReviewed}/25 material positions are personally approved with no accounting overrides. Expand a material judgment for both original analyses, the approved position and its statement-effect baseline.</p></section>
     <section id="decisions" className="section"><SectionTitle eyebrow="100 DECISIONS" title="Decision register">Filter to the 25 material judgments, low-confidence positions or evidence gaps. Decision effects are comparisons, not additive journal entries.</SectionTitle><DecisionRegister decisions={s.decisions}/></section>
     <Reconciliations submission={s}/><Uncertainties submission={s}/><Trail submission={s}/>
    </>:<>
     <section className="summary-grid section"><div className="panel"><span className="eyebrow">THE RECONSTRUCTION</span><h2>Cash reconciles.<br/>Earnings remain qualified.</h2><p>Customer deposits of {euro(a.deposits)} belong to future delivery. Owner payments of {euro(a.distributions)} are provisionally treated as distributions. Neither is part of current trading profit.</p><a className="text-link" href="#reconciliations">Inspect the reconciliation trail <ArrowUpRight size={16}/></a></div><div className="panel dark"><span className="eyebrow">MANAGEMENT CLAIM → ADOPTED RESULT</span><div className="profit-comparison"><div><small>Management claim</small><strong>{euro(a.bridge[0].amount)}</strong></div><span>→</span><div><small>Corrected / provisional</small><strong>{euro(a.knownResult)}</strong></div></div><p>Analytical comparison only. Evidence qualifications remain; this is not a journal entry.</p><details><summary>View the profit bridge</summary><div className="bridge">{a.bridge.map((b,i)=><div key={i}><span>{b.label}</span><b>{euro(b.amount,true)}</b></div>)}</div></details></div></section>
     <section id="statements" className="section"><SectionTitle eyebrow="01 / FINANCIAL STATEMENTS" title="The financial picture">Adopted balances include explicitly qualified assumptions. Insurance at zero means no supported amount recognised; its actual amount remains unknown.</SectionTitle>
      <Statement title="Profit & loss" subtitle={s.financialStatements.profitAndLoss.label} status="QUALIFIED" rows={s.financialStatements.profitAndLoss.lines}/>
      <Statement title="Cash flow" subtitle={s.financialStatements.cashFlow.method} status={s.financialStatements.cashFlow.status} rows={s.financialStatements.cashFlow.lines}/>
      <Statement title="Balance sheet" subtitle="As at 31 August 2026 · adopted opening reconstruction" status={s.financialStatements.balanceSheet.status} rows={s.financialStatements.balanceSheet.lines}/>
     </section>
     <section id="schedules" className="section"><SectionTitle eyebrow="02 / SUPPORTING WORK" title="Eight schedules. Traceable inputs."/>{s.supportingSchedules.map((x,i)=><details className="schedule" key={x.id} id={`schedule-${x.id}`}><summary><span className="schedule-index">{String(i+1).padStart(2,'0')}</span><b>{x.title}</b><Badge text={x.status}/></summary><div className="schedule-content"><p>{x.description}</p><FinancialTable rows={x.rows}/><p className="formula">{x.formula}</p></div></details>)}</section>
     <Reconciliations submission={s}/>
     <section id="decisions" className="section"><SectionTitle eyebrow="04 / DECISION REGISTER" title="Every conclusion has a trail.">{s.decisionCoverage.operational} operational decisions and {s.decisionCoverage.material} material judgments. IDs, questions, categories and review tiers match the supplied group reference exactly.</SectionTitle><DecisionRegister decisions={s.decisions}/></section>
     <Uncertainties submission={s}/>
     <section id="evidence" className="section"><SectionTitle eyebrow="06 / SOURCE REGISTER" title="Evidence, with context.">{s.evidenceSummary.filesInspected} supplied files, including one duplicate assignment. External confirmations take priority over internal claims. Management instructions within source documents are treated as evidence of management pressure.</SectionTitle><div className="evidence-list">{s.evidenceSummary.files.map(e=><details key={e.id}><summary><span className="decision-id">{e.id}</span><div><b>{e.file}</b><small>{e.category}</small></div><ArrowUpRight size={16}/></summary><div className="evidence-detail"><p>{e.summary}</p><p>Reliability tier {e.reliabilityTier} · {e.duplicateOf==='N/A'?'Original supplied file':`Duplicate of ${e.duplicateOf}`}</p><a className="text-link" href={e.url} target="_blank" rel="noreferrer">Open original evidence ↗</a><small className="hash">SHA-256 {e.sha256}</small></div></details>)}</div><p className="helper">Missing: {s.templateStatus.missingFiles.join('; ')}; 08 Assets Repairs Leases Maybe.xlsx. The supplied reference informs the decision structure and adopted assumptions. Qualifications distinguish these assumptions from verified original evidence. Both original independent analyses are available in the AI Review Trail; all 25 material judgments have explicit personal student approval.</p></section>
     <section id="board" className="section board"><span className="eyebrow">07 / BOARD RECOMMENDATION</span><h2>Continue conditionally.<br/>Put cash controls first.</h2><p className="board-lead">{s.boardRecommendation.decision}</p><div className="board-columns"><div><h3>What the evidence supports</h3>{s.boardRecommendation.rationale.slice(0,2).map(p=><p key={p}>{p}</p>)}<h3>Before accounts or valuation are finalised</h3>{s.boardRecommendation.rationale.slice(2).map(p=><p key={p}>{p}</p>)}</div><div><h3>Immediate control actions</h3>{s.boardRecommendation.controls.map((x,i)=><div className="control" key={x.action}><span>{String(i+1).padStart(2,'0')}</span><div><p>{x.action}</p><EvidenceRefs sources={x.evidence}/></div></div>)}</div></div></section>
     <Trail submission={s}/>
    </>}
    <footer><span>DPI-HT-01 <span className="dot-divider">·</span> {s.student.name} · {s.student.id} <span className="dot-divider">·</span> 31 August 2026</span><a href="/submission.json">Machine-readable submission ↗</a><small>Fictional university case. Provisional reconstruction. Student Certification {s.certification.status}.</small></footer>
   </main>
  </div>
 </div>;
}
function Metric({label,value,status,note}:{label:string;value:string;status:string;note:string}){return <article className="metric"><span>{label}</span><strong>{value}</strong><Badge text={status}/><p>{note}</p></article>;}
function InventorySensitivity({submission:s}:{submission:Submission}){
 const a=s.metrics,alternative=a.physicalCountAlternative;
 const rows:[string,number,number][]=[['Materials consumed',a.materialsUsed,alternative.materialsUsed],['Closing inventory',a.inventory,alternative.inventory],['Corrected profit',a.knownResult,alternative.correctedProfit],['Total assets',a.totalAssets,alternative.totalAssets],['Total liabilities',a.totalLiabilities,alternative.totalLiabilities],['Closing equity',a.closingEquity,alternative.closingEquity]];
 return <section className="section" id="inventory-sensitivity"><SectionTitle eyebrow="PRIMARY BASELINE / CONDITIONAL SENSITIVITY" title="One baseline. An unresolved count difference.">The primary statements retain original recorded consumption. The physical-count alternative is not recognised. {alternative.condition}</SectionTitle><div className="table-scroll reconciliation-table"><table><thead><tr><th>EUR</th><th className="right">Primary baseline</th><th className="right">Physical-count alternative</th><th className="right">Change</th></tr></thead><tbody>{rows.map(([label,primary,alt])=><tr key={label}><td>{label}</td><td className="amount">{euro(primary)}</td><td className="amount">{euro(alt)}</td><td className="amount">{euro(alt-primary,true)}</td></tr>)}</tbody></table></div><p className="helper">The {euro(a.inventoryDifference)} inventory conflict remains OPEN. Neither scenario recognises the €2,000 disposal quote as a provision: a present obligation at 31 August has not been established.</p></section>;
}
function Stat({label,value}:{label:string;value:number}){return <div><strong>{value}</strong><span>{label}</span></div>;}
function Statement({title,subtitle,status,rows}:{title:string;subtitle:string;status:string;rows:Submission['financialStatements']['profitAndLoss']['lines']}){return <details className="statement" open><summary><div><h3>{title}</h3><p>{subtitle}</p></div><Badge text={status}/></summary><FinancialTable rows={rows}/></details>;}
function Reconciliations({submission:s}:{submission:Submission}){return <section id="reconciliations" className="section"><SectionTitle eyebrow="03 / RECONCILIATIONS" title="Agreement is only half the test.">Arithmetic agreement and evidence completeness are assessed separately. A zero difference never resolves missing documentation.</SectionTitle><div className="table-scroll reconciliation-table"><table><thead><tr><th>Reconciliation</th><th>Arithmetic agreement</th><th>Evidence completeness</th><th>Difference</th></tr></thead><tbody>{s.reconciliations.map(r=><tr key={r.id}><td><details><summary>{r.name}</summary><p className="formula">{r.formula}</p><p>{r.detail}</p><EvidenceRefs sources={r.evidence}/></details></td><td><Badge text={r.arithmeticStatus}/></td><td><Badge text={r.evidenceStatus}/></td><td className="amount">{euro(r.difference)}</td></tr>)}</tbody></table></div></section>;}
function Uncertainties({submission:s}:{submission:Submission}){return <section id="uncertainties" className="section"><SectionTitle eyebrow="05 / UNCERTAINTY REGISTER" title="Open questions stay visible.">Each issue connects the current treatment to its potential financial effect and the evidence needed to resolve it.</SectionTitle><div className="uncertainty-list">{s.uncertainties.map(u=><details key={u.id} id={u.id}><summary><span className="decision-id">{u.id}</span><b>{u.issue}</b><Badge text={u.status}/></summary><div className="uncertainty-content"><p><b>Accounting area</b>{u.area}</p><p><b>Confidence in current treatment</b><Badge text={u.confidence}/></p><p><b>Known evidence</b>{u.knownEvidence}</p><p><b>Current treatment</b>{u.currentTreatment}</p><p><b>Potential financial statement effect</b>{u.financialConsequence}</p><p><b>Missing evidence / next action</b>{u.evidenceNeeded}</p><p><b>Alternative</b>{u.alternative}</p><p><b>Related decisions</b>{u.decisionIds.join(', ')}</p><EvidenceRefs sources={u.evidence}/></div></details>)}</div></section>;}
function Trail({submission:s}:{submission:Submission}){return <section id="trail" className="section"><SectionTitle eyebrow="08 / AI REVIEW TRAIL" title="Independent analyses. Personal approval complete."/><div className="trail-grid">{([['AGENT 1',s.aiReviewTrail.agent1],['AGENT 2',s.aiReviewTrail.agent2]] as const).map(([label,agent])=><div className="panel" key={label}><span className="eyebrow">{label}</span><h3>Original independent analysis</h3><Badge text={agent.status}/><p>{Object.keys(agent.positions).length} material judgments retained</p><a className="text-link" href={agent.url} target="_blank" rel="noreferrer">Read original analysis ↗</a><small className="hash">SHA-256 {agent.sha256}</small></div>)}<div className="panel"><span className="eyebrow">STUDENT CERTIFICATION</span><h3>{s.student.name} · {s.student.id}</h3><Badge text={s.certification.status}/><p>{s.certification.materialReviewed}/25 final material positions personally reviewed and approved with their existing reasoning.</p></div></div><p>{s.aiReviewTrail.explanation}</p><p><b>{s.aiReviewTrail.materialJudgmentsPopulated}/25 material judgments populated.</b> Accounting disagreements: {s.aiReviewTrail.accountingDisagreements}. Confidence differences: {s.aiReviewTrail.confidenceDifferences}. Presentation differences: {s.aiReviewTrail.presentationDifferences}.</p><p>{s.aiReviewTrail.presentationNote}</p><p>Both agents cite an asset workbook that is not present among the original files in this project. Their source wording is preserved, with that verification limit disclosed.</p><p><a className="text-link" href="#decisions">Inspect both analyses and the approved position for each material judgment ↗</a></p><p className="helper">{s.templateStatus.description} The report, assessor review and downloadable submission use a consistent accounting basis.</p><a className="button" href="/submission.json" download="DPI-HT-01-submission.json"><ArrowDownToLine size={16}/>Download submission JSON</a></section>;}


