import type { Accounts } from './accounting';
import { facts, payroll, bank } from '@/data/inputs';
import { refs } from '@/data/evidence';
import type { Reconciliation } from './types';
import { num } from './formatting';
export function reconciliations(a:Accounts) {
 const check=(id:string,name:string,status:Reconciliation['status'],formula:string,difference:Reconciliation['difference'],detail:string,evidence:Reconciliation['evidence'],uncertaintyIds:string[]=[]):Reconciliation=>({id,name,status,formula,difference,detail,evidence,uncertaintyIds});
 const rows:Reconciliation[] = [
 check('cash-bank','Cash to bank',a.closingCash===facts.confirmedCash&&a.bankClosingCash===facts.confirmedCash?'PASS':'OPEN',`${num(a.closingCash)} reconstructed = ${num(a.bankClosingCash)} bank = ${num(facts.confirmedCash)} external confirmation`,a.closingCash-facts.confirmedCash,'Confirmed bank cash only; not a conclusion about liquidity adequacy.',refs.bank),
 check('cash-flow','Cash-flow roll-forward',a.closingCash===a.bankClosingCash?'PASS':'OPEN',`${num(a.openingCash)} + ${num(a.cfo)} − ${num(-a.cfi)} − ${num(-a.cff)} = ${num(a.closingCash)}`,a.closingCash-a.bankClosingCash,'Opening credit is not counted as a period receipt.',refs.bank),
 check('ar','Revenue / receivables','QUALIFIED',`${num(a.revenue)} − ${num(a.customerReceipts)} − ${num(facts.badDebt)} = ${num(a.netAR)}`,a.revenueRows.reduce((n,c)=>n+c.grossAR,0)-facts.badDebt-a.netAR,'Identified balances reconcile. Opening AR completeness and web fulfilment remain qualified.',refs.revenue,['U03','U10']),
 check('inventory','Primary inventory / COGS','QUALIFIED',`${num(facts.openingInventory)} + ${num(a.purchases)} − ${num(a.materialsUsed)} − ${num(facts.damagedStock)} = ${num(a.inventory)}`,facts.openingInventory+a.purchases-a.materialsUsed-facts.damagedStock-a.inventory,'Original materials consumed retained. The roll-forward agrees arithmetically; the physical-count difference remains separately open.',refs.inventory,['U01']),
 check('inventory-conflict','Physical count / warehouse roll-forward conflict','OPEN',`${num(a.physicalInventory)} physical usable count − ${num(a.inventory)} primary closing inventory = ${num(a.inventoryDifference)}`,a.inventoryDifference,'Unresolved source conflict. The physical-count model remains a conditional sensitivity; no additional expense or balancing entry.',refs.inventory,['U01']),
 check('inventory-alternative','Physical-count sensitivity roll-forward','QUALIFIED',`${num(facts.openingInventory)} + ${num(a.purchases)} − ${num(a.physicalCountAlternative.materialsUsed)} − ${num(facts.damagedStock)} = ${num(a.physicalInventory)}`,facts.openingInventory+a.purchases-a.physicalCountAlternative.materialsUsed-facts.damagedStock-a.physicalInventory,a.physicalCountAlternative.condition,refs.inventory,['U01']),
 check('ap','Purchases / AP','QUALIFIED',`${num(a.inferredOpeningAP)} inferred + ${num(a.purchases)} − ${num(a.supplierPayments)} = ${num(a.ap)}`,a.inferredOpeningAP+a.purchases-a.supplierPayments-a.ap,'Arithmetic closes because opening AP is inferred. Closing AP is independently confirmed.',refs.purchases,['U03']),
 check('payroll','Payroll','QUALIFIED',`${num(facts.openingPayroll)} + ${num(a.payrollExpense)} − ${num(a.payrollCash)} = ${num(a.payrollClosing)}`,payroll.reduce((n,p)=>n+p.paid,0)-a.payrollCash,'Aggregate employee expense and cash agree. Monthly and departmental opening balances missing.',refs.payroll,['U07']),
 check('ppe','PPE cost / accumulated depreciation','QUALIFIED',`Gross ${num(a.openingGrossPPE)} + ${num(a.capex)} = ${num(a.closingGrossPPE)}; accumulated depreciation ${num(a.openingAccumulatedDepreciation)} + ${num(a.depreciation)} = ${num(a.closingAccumulatedDepreciation)}; net ${num(a.netPPE)}`,a.openingGrossPPE+a.capex-a.openingAccumulatedDepreciation-a.depreciation-a.netPPE,'Arithmetic agrees with the adopted assumptions. Original invoices verify additions only; opening PPE and depreciation require the missing asset workbook.',refs.ppe,['U04']),
 check('debt','Debt principal',a.debtClosing===facts.confirmedLoan?'PASS':'OPEN',`${num(facts.openingLoan)} + ${num(a.borrowing)} − ${num(a.principalRepaid)} = ${num(a.debtClosing)}`,a.debtClosing-facts.confirmedLoan,'Principal agrees with external confirmation. Maturity classification is separately unresolved.',refs.debt),
 check('interest','Interest expense / paid / payable','QUALIFIED',`${num(a.inferredOpeningInterest)} inferred + ${num(facts.interestExpense)} − ${num(a.interestPaid)} = ${num(facts.confirmedInterestPayable)}`,a.inferredOpeningInterest+facts.interestExpense-a.interestPaid-facts.confirmedInterestPayable,'Closing accrual externally confirmed; zero opening interest is inferred, not independently evidenced.',refs.debt,['U03']),
 check('equity','Equity roll-forward','QUALIFIED',`${num(a.openingEquity)} opening + ${num(a.knownResult)} profit − ${num(a.distributions)} distributions = ${num(a.closingEquity)}`,a.openingEquity+a.knownResult-a.distributions-a.closingEquity,'Opening equity is an adopted reconstruction assumption that is not independently verified from the available original capital records.',refs.owner,['U02','U03','U04','U08','U09']),
 check('balance-sheet','Balance sheet','QUALIFIED',`${num(a.totalAssets)} assets = ${num(a.totalLiabilities)} liabilities + ${num(a.closingEquity)} equity`,a.totalAssets-a.totalLiabilities-a.closingEquity,'Adopted balances arithmetically agree. Opening balances, insurance and other completeness exposures remain qualified.',refs.missing,['U01','U02','U03','U04','U09']),
 check('indirect-cfo','Indirect CFO — primary model cross-check','QUALIFIED',`${num(a.knownResult)} profit + non-cash adjustments + working-capital changes = ${num(a.conditionalIndirectCFO)}`,a.conditionalIndirectCFO-a.cfo,'Adds depreciation, stock write-off, bad debt and provisions once; uses gross receivables and gross recorded inventory movements. Opening AR/AP and asset assumptions remain qualified.',refs.bank,['U01','U02','U03','U04','U09']),
 check('alternative-balance-sheet','Physical-count sensitivity balance sheet','QUALIFIED',`${num(a.physicalCountAlternative.totalAssets)} alternative assets = ${num(a.physicalCountAlternative.totalLiabilities)} liabilities + ${num(a.physicalCountAlternative.closingEquity)} alternative equity`,a.physicalCountAlternative.totalAssets-a.physicalCountAlternative.totalLiabilities-a.physicalCountAlternative.closingEquity,'Sensitivity only. Assets, profit and equity each rise by the same inventory difference if the count and lower consumption are substantiated. Cash, debt and other liabilities are unchanged.',refs.inventory,['U01','U03','U04']),
 check('management','Management-profit bridge','QUALIFIED',`${num(facts.managementProfit)} + analytical aggregate replacements = ${num(a.knownResult)}`,a.bridge.reduce((n,r)=>n+r.amount,0)-a.knownResult,'Analytical bridge, not journals. Does not establish the detailed composition of management aggregates or final profit.',refs.management,['U02','U04','U09']),
 ];
 return rows.map(r=>{
  const status=typeof r.difference==='number'&&r.difference!==0?'OPEN' as const:r.status;
  return {...r,status,arithmeticStatus:typeof r.difference!=='number'?'NOT DETERMINABLE':r.difference===0?'PASS':'OPEN',evidenceStatus:status};
 });
}
export function bankRunningDifferences() {return bank.slice(1).map((b,i)=>({reference:b.reference,difference:bank[i].balance+b.credit-b.debit-b.balance}));}
